# Generated by Django 4.0.1 on 2022-01-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name here', max_length=100, unique=True)),
                ('creators', models.CharField(default='no creators listed', max_length=100)),
                ('alter_ego', models.CharField(default='no alter ego listed', max_length=100)),
                ('place_of_residence', models.CharField(default='no place of residence', max_length=100)),
                ('description', models.TextField(default='no description')),
                ('origin_story', models.TextField(default='no origin listed')),
                ('career', models.TextField(default='no career listed', max_length=100)),
                ('image_url', models.TextField(default='no image given')),
                ('aliases', models.CharField(default='no aliases listed', max_length=100)),
                ('powers', models.CharField(default='no powers listed', max_length=300)),
                ('comics', models.TextField(default='no comics')),
                ('movies', models.TextField(default='no movies')),
                ('other_forms_of_media', models.TextField(default='no media given')),
            ],
        ),
        migrations.CreateModel(
            name='SuperVillain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name here', max_length=100, unique=True)),
                ('creators', models.CharField(default='no creators listed', max_length=100)),
                ('alter_ego', models.CharField(default='no alter ego listed', max_length=100)),
                ('place_of_residence', models.CharField(default='no place of residence', max_length=100)),
                ('description', models.TextField(default='no description')),
                ('origin_story', models.TextField(default='no origin listed')),
                ('career', models.TextField(default='no career listed', max_length=100)),
                ('image_url', models.TextField(default='no image given')),
                ('aliases', models.CharField(default='no aliases listed', max_length=100)),
                ('powers', models.CharField(default='no powers listed', max_length=300)),
                ('comics', models.TextField(default='no comics')),
                ('movies', models.TextField(default='no movies')),
                ('other_forms_of_media', models.TextField(default='no media given')),
            ],
        ),
    ]
