# Generated by Django 4.0.1 on 2022-01-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superhero_database_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSuperVillain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=100)),
                ('author', models.CharField(default='no author', max_length=100)),
                ('body', models.TextField()),
                ('supervillain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='superhero_database_app.supervillain')),
            ],
        ),
        migrations.CreateModel(
            name='PostSuperHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=100)),
                ('author', models.CharField(default='no author', max_length=100)),
                ('body', models.TextField()),
                ('superhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='superhero_database_app.superhero')),
            ],
        ),
        migrations.CreateModel(
            name='CommentSuperVillain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='no author', max_length=100)),
                ('body', models.TextField()),
                ('post_supervillain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='superhero_database_app.postsupervillain')),
            ],
        ),
        migrations.CreateModel(
            name='CommentSuperHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='no author', max_length=100)),
                ('body', models.TextField()),
                ('post_superhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='superhero_database_app.postsuperhero')),
            ],
        ),
    ]
