# Generated by Django 4.0.1 on 2022-01-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superhero_database_app', '0002_postsupervillain_postsuperhero_commentsupervillain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHeroComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='no author', max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperHeroPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=100)),
                ('author', models.CharField(default='no author', max_length=100)),
                ('body', models.TextField()),
                ('superhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superhero_posts', to='superhero_database_app.superhero')),
            ],
        ),
        migrations.CreateModel(
            name='SuperVillainComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='no author', max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperVillainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=100)),
                ('author', models.CharField(default='no author', max_length=100)),
                ('body', models.TextField()),
                ('supervillain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervillain_posts', to='superhero_database_app.supervillain')),
            ],
        ),
        migrations.RemoveField(
            model_name='commentsupervillain',
            name='post_supervillain',
        ),
        migrations.RemoveField(
            model_name='postsuperhero',
            name='superhero',
        ),
        migrations.RemoveField(
            model_name='postsupervillain',
            name='supervillain',
        ),
        migrations.DeleteModel(
            name='CommentSuperHero',
        ),
        migrations.DeleteModel(
            name='CommentSuperVillain',
        ),
        migrations.DeleteModel(
            name='PostSuperHero',
        ),
        migrations.DeleteModel(
            name='PostSuperVillain',
        ),
        migrations.AddField(
            model_name='supervillaincomment',
            name='supervillain_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervillain_comments', to='superhero_database_app.supervillainpost'),
        ),
        migrations.AddField(
            model_name='superherocomment',
            name='superhero_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superhero_comments', to='superhero_database_app.superheropost'),
        ),
    ]
